# Generated by Django 3.2 on 2021-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=650)),
                ('cone', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('ctwo', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('cthree', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('cfour', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('info', models.CharField(max_length=650)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
