# Generated by Django 3.2 on 2021-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210408_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cfour',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cone',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cthree',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='ctwo',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
